title: "Madhulika Badanpet"
name: "Madhulika Badanpet"
description: "Sr. Client Systems Engineer @ Snowflake, driving innovation in enterprise IT by combining Windows endpoint automation, Zero Trust security, and data-driven insights to transform modern endpoint management and IT operations at scale."
url: "https://mbadanpet.github.io"  
baseurl: ""                           
repository: mbadanpet/mbadanpet.github.io

# Theme (remote)
remote_theme: "qwtel/hydejack"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

# Plugins (all supported by GitHub Pages)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-paginate

# Author profile (shows on About page and sidebar if enabled)
author:
  name: "Madhulika Badanpet"
  email: "mbadanpet@gmail.com"
  about: "Sr. Client Systems Engineer @ Snowflake, driving innovation in enterprise IT by combining Windows endpoint automation, Zero Trust security, and data-driven insights to transform modern endpoint management and IT operations at scale."
  picture: /assets/images/avatar.jpg
  social:
    github: mbadanpet
    linkedin: https://www.linkedin.com/in/madhulika-badanpet-a6093655/

# Taxonomies
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Navigation (uses _data/navigation.yml)
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true

# Defaults (front matter fallbacks)
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      comments: false  # can enable if you add a provider

hydejack:
  cover: /assets/images/header.jpg
