title: "Madhulika Badanpet"
name: "Madhulika Badanpet"
description: "Sr. Client Systems Engineer @ Snowflake, driving innovation in enterprise IT by combining Windows endpoint automation, Zero Trust security, and data-driven insights to transform modern endpoint management and IT operations at scale."
url: "https://mbadanpet.github.io"
baseurl: ""
repository: mbadanpet/mbadanpet.github.io

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
theme: null
minimal_mistakes_skin: "air"   # options: default, air, aqua, dark, dirt, neon, mint, plum, sunrise

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-paginate

# Author profile
author:
  name: "Madhulika Badanpet"
  avatar: "/assets/images/avatar.jpg"
  bio: "Sr. Client Systems Engineer @ Snowflake, driving innovation in enterprise IT by combining endpoint automation, Zero Trust, and data-driven insights to transform modern endpoint management and IT operations at scale."
  location: "USA"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/madhulika-badanpet-a6093655/"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/mbadanpet"

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Collections
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true

# Defaults for posts
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      comments: false

sass:
  style: compressed

breadcrumbs: true
